sudo: required
services:
- docker
env:
- CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- curl https://sdk.cloud.google.com | bash
- exec -l $SHELL
- gcloud init
- gcloud components install kubectl
- docker run --name mongo -p 27017:27017 -d mongo:3.2 
- docker run --name redis -p 6379:6379 -d redis:3.0 
- sleep 30s
- docker exec $(docker ps -aqf "name=mongo") mongo _GLOBAL --eval "db.getCollection('_Settings').insertOne({secureKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',clusterKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',myURL:'http://localhost:4730'});"
- git clone https://github.com/cloudboost/javascriptsdk
- npm install grunt-cli -g
- mkdir config
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in smtp.json.enc -out config/smtp.json -d
install:
- cd javascriptsdk
- npm install
- grunt
- cd ..
- docker build -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/cloudboost:latest .
- docker run --name cloudboost -p 4730:4730 -it --link redis:redis --link mongo:mongo -d cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER 
- sleep 30s
- cd javascriptsdk
- npm test
