sudo: required
services:
- docker
language: node_js
node_js:
- '6'
before_install:

install:
- docker build -t cloudboost/cloudboost:latest -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER
  .
- docker run --name redis -p 6379:6379 -p 16379:16379 -p 26379:26379 -it redis:3.0
- docker run --name mogno -p 27017:27017 -it mongo:3.2
- docker run --name cloudboost -p 4730:4730 -it cloudboost/cloudboost:latest
