sudo: required
services:
- docker
language: node_js
node_js:
- '6'
before_install:
- touch config\\smtp.json
- touch config\\key.key
- touch config\\cert.crt
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in cert.crt.enc -out config\\cert.crt -d
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in key.key.enc -out config\\key.key -d
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in smtp.json.enc -out config\\smtp.json -d
install:
- docker build -t cloudboost/cloudboost:latest -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER
  .
- git clone https://github.com/cloudboost/docker
- cd docker
- docker compose up
