sudo: required
services:
- docker
language: node_js
node_js:
- '6'
before_install:

install:
- docker build -t cloudboost/cloudboost:latest -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER
  .
- git clone https://github.com/cloudboost/docker
- cd docker
- docker-compose up
