language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in config/key.key.enc -out config/key.key -d
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in config/cert.crt.enc -out config/cert.crt -d
- openssl aes-256-cbc -K $encrypted_f0b486ccf91b_key -iv $encrypted_f0b486ccf91b_iv
  -in config/smtp.json.enc -out config/smtp.json -d
